### ISSUE TITLE
Failed to build TsDemuxPluginVLC, reason dvbpsi.h does not exist

### ISSUE THREAD

**Issue by MartinEesmaa** [InterDigitalInc/VTMDecoder_VLCPlugin#5]
Hello! I followed the instructions how to build TsDemuxPluginVLC, I added entries including dvbpsi, configured and generated.
I build using code `make -j` and then I got an error code:
```
[ 78%] Built target dvbpsi
[ 79%] Building C object CMakeFiles/vctsdemux_plugin.dir/ts.c.o
In file included from /home/unknown/GitHub/VTMDecoder_VLCPlugin/TsDemuxPluginVLC/ts.c:44:
/home/unknown/GitHub/vlc-3.0.9.2/src/modules/demux/mpeg/ts_psip.h:25:11: fatal error: dvbpsi/dvbpsi.h: No such file or directory
   25 |  #include <dvbpsi/dvbpsi.h>
      |           ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vctsdemux_plugin.dir/build.make:63: CMakeFiles/vctsdemux_plugin.dir/ts.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/vctsdemux_plugin.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

And here's my second try, but it failed too:
```
[ 78%] Built target dvbpsi
Scanning dependencies of target vctsdemux_plugin
[ 79%] Building C object CMakeFiles/vctsdemux_plugin.dir/ts.c.o
In file included from /home/unknown/GitHub/VTMDecoder_VLCPlugin/TsDemuxPluginVLC/ts.c:44:
/home/unknown/GitHub/vlc-3.0.9.2/src/modules/demux/mpeg/ts_psip.h:25:11: fatal error: dvbpsi/dvbpsi.h: No such file or directory
   25 |  #include <dvbpsi/dvbpsi.h>
      |           ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vctsdemux_plugin.dir/build.make:63: CMakeFiles/vctsdemux_plugin.dir/ts.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/vctsdemux_plugin.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I don't understand what I do patch ES format? I don't understand what is ES format?

My operating system (virtualization) on Ubuntu 20.04.4 LTS
VLC target build: VLC 3.0.9.2

- Martin Eesmaa

**Comment by FabriceUrban** [comment]
Hi,
I Assume this comes late, but:
- First, this concerns only the ts demux. You need this only if you have ts files containing VVC stream to decode. 
- As a workaround, you can also specify the details with the --ts-extra-pmt option (instead of modifying the demux)
- If you still want to go on, instructions with DVBPSI are for a windows build (Visual).  For linux, build vlc with a patched ts_psi.c. To patch the file just modify the ts_psi.c file with the lines containing "VLC_CODEC_VVC" and "VVC" (total of 5 lines to add).

**Comment by MartinEesmaa** [comment]
@FabriceUrban, here's my new issue of two days ago: https://pastebin.com/E4tNsJ43

**Comment by MartinEesmaa** [comment]
I should give try for Linux, if possible.

**Comment by FabriceUrban** [comment]
last commit fixes a few things for linux compilation (not tested before) ...

**Comment by MartinEesmaa** [comment]
@FabriceUrban, thanks, now it's success compiled, see result of Linux screenshot:
https://github.com/MartinEesmaa/VVCEasy/tree/master/INSTALLVLCPLUGIN#for-linux-users
