### ISSUE TITLE
VLC plugin decodes raw VVC, but not VVC in MP4

### ISSUE THREAD

**Issue by LigH-de** [InterDigitalInc/VTMDecoder_VLCPlugin#6]
I successfully installed the plugin DLL's in VLC, it nicely plays raw *.266 video streams encoded by uvg266.

So I used MP4Box to multiplex it in MP4, to find a supported file type in the Open dialog (unfortunately, the plugin seems not to be able to add file name extensions).

Unfortunately, VLC did not display any visible video, although it played for the expected time. I guess the VideoLAN team needs to add support for VVC video streams to their MP4 demultiplexer then?

**Comment by FabriceUrban** [comment]
Hi,
Yes I think the MP4 demux has to be modified.
